enum Page {
  LOADING_TRIALS,
  CONSENT,
  INTRODUCTION,
  TRIALS,
  DEMOGRAPHICS_INSTRUCTIONS,
  DEMOGRAPHICS,
  DEBRIEFING,
}

const PAGE_ORDER = [
  Page.CONSENT,
  Page.INTRODUCTION,
  Page.LOADING_TRIALS,
  Page.TRIALS,
  Page.DEMOGRAPHICS_INSTRUCTIONS,
  Page.DEMOGRAPHICS,
  Page.DEBRIEFING,
];
